### ISSUE TITLE
Failed ping tests

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-probe#133]
```
Checking for the latest version
Current version 0.20.0
Latest version 0.20.0
[2023-05-05 09:20:09] [INFO] [687] [general] Start probe version 0.20.0 in a production mode
[2023-05-05 09:20:09] [DEBUG] [687] [general] connection to API established
[2023-05-05 09:20:09] [INFO] [687] [api:connect] connected from (Tel Aviv, IL, AS) (lat: 32.0809 long: 34.7806)
[2023-05-05 09:20:24] [WARN] [687] [status-manager] ping test promise rejected: Command failed with exit code 1: unbuffer ping -4 -c 6 -i 0.2 -w 15 j.root-servers.net
PING  (192.58.128.30) 56(84) bytes of data.

---  ping statistics ---
74 packets transmitted, 0 received, 100% packet loss, time 14889ms

{
  shortMessage: 'Command failed with exit code 1: unbuffer ping -4 -c 6 -i 0.2 -w 15 j.root-servers.net',
  command: 'unbuffer ping -4 -c 6 -i 0.2 -w 15 j.root-servers.net',
  escapedCommand: 'unbuffer ping -4 -c 6 -i 0.2 -w 15 j.root-servers.net',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'PING  (192.58.128.30) 56(84) bytes of data.\n' +
    '\n' +
    '---  ping statistics ---\n' +
    '74 packets transmitted, 0 received, 100% packet loss, time 14889ms\n',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Command failed with exit code 1: unbuffer ping -4 -c 6 -i 0.2 -w 15 j.root-servers.net
PING  (192.58.128.30) 56(84) bytes of data.

---  ping statistics ---
74 packets transmitted, 0 received, 100% packet loss, time 14889ms

    at makeError (file:///app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///app/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 2)
    at async StatusManager.pingTest (file:///app/dist/lib/status-manager.js:49:25)
    at async StatusManager.runTest (file:///app/dist/lib/status-manager.js:36:24)
    at async StatusManager.start (file:///app/dist/lib/status-manager.js:19:9)
    at async Socket.<anonymous> (file:///app/dist/helper/api-connect-handler.js:8:5)
```

This seems to be a QA test with 100% packet loss. But it seems to be treated like a fatal error?
Normally when QA doesnt pass we say `[status-manager] ping test result don't match criterias:` but not in this case

**Comment by MartinKolarik** [comment]
`Command failed with exit code 1` that's an error, yes.

**Comment by alexey-yarmosh** [comment]
There are two reasons when single ping request will be treated as non-successful for status manager:
1. `execa` ping request rejects
2. `execa` ping request resolves, but result have non-zero packet loss

When there are 2 of such a non-successful results (reason may be any of 2 above) probe is treated "not ready".

For some reason `execa` resolves requests with non-100% packet loss, but rejects requests with 100% packet loss.
- so when we get e.g. 80% packet loss, request resolves but doesn't match criterias and we see `ping test result don\'t match criterias: ...` in the logs
- but when we get 100% packet loss (case from the issue), request rejects and we see `ping test promise rejected: ...` in the logs

The only difference is the log message, that doesn't affect the logic of status-manager in any way. I think we can close the issue.

**Comment by jimaek** [comment]
But why it's a fatal error?

**Comment by alexey-yarmosh** [comment]
What do you mean by fatal? Does app crashed?

**Comment by jimaek** [comment]
The app I guess not, but something didn't exit properly due to `Error: Command failed with exit code 1`

Under normal conditions this shouldn't happen, that's why I open the task to understand why it happened
